"""Deterministic, offline "model" for RAG.

Real RAG answers are generated by an LLM from the retrieved context. To keep the
project runnable with **zero keys**, this mock produces a genuinely *grounded,
extractive* answer: it reads the numbered context block out of the prompt and
returns the most relevant sentences from the top-ranked source, with a citation.

It's not fluent prose — that's what a real model is for
(``LLM_PROVIDER=openai|anthropic|ollama``) — but it proves the retrieval and
citation plumbing end-to-end and makes the tests deterministic.
"""

from __future__ import annotations

import re

from .base import ChatModel, Message

_CONTEXT = re.compile(r"Context:\n(.*)\n\nQuestion:", re.DOTALL)
_SENTENCE = re.compile(r"(?<=[.!?])\s+")


class MockChatModel(ChatModel):
    name = "mock"

    def complete(self, messages: list[Message], *, temperature: float = 0.0, max_tokens: int = 1024) -> str:
        user = next((m.content for m in reversed(messages) if m.role == "user"), "")
        match = _CONTEXT.search(user)
        if not match or not match.group(1).strip():
            return "I don't know based on the provided documents."

        blocks = re.split(r"\n\n(?=\[\d+\])", match.group(1).strip())
        top = blocks[0]
        lines = top.splitlines()
        body = "\n".join(lines[1:]).strip() if lines and lines[0].startswith("[") else top
        snippet = _first_sentences(body, 2)
        return f"{snippet} [1]"


def _first_sentences(text: str, n: int) -> str:
    text = " ".join(text.split())
    sentences = _SENTENCE.split(text)
    return " ".join(sentences[:n]).strip()
